# Site info
name: Joomlatools Developer
url: http://developer.joomlatools.com
main_title: Joomlatools - Joomla extensions that just work!
description: We're a close-knit team of product designers who help grow businesses and work to create simple and powerful Joomla extensions.
domain: developer.joomlatools.com

# Blog separator
excerpt_separator: <!--more-->

# We don't want to publish some files
exclude: [
  'bower_components',
  'node_modules',
  '.gitignore',
  'bower.json',
  'Gemfile',
  'Gemfile.lock',
  'gruntfile.js',
  'package.json',
  'README.md'
]