default: preface/introduction

pages:
   Preface:
      Introduction: preface/introduction
      Contributing: preface/contributing
      License: preface/license
   Tools:
      Composer: tools/composer
      Vagrant: tools/vagrant