#!/bin/bash
BRANCH="staging"
DATASOURCE="http://support.joomlatools.xxx"

ROOT="/var/www/developer.joomlatools.xxx"
TMP_CLONE="/tmp/developer.joomlatools.xxx"

source /etc/profile # Make sure RVM can be found

while read oldrev newrev REF
do
    CURRENT_BRANCH=$(git rev-parse --symbolic --abbrev-ref $REF)
    CHANGELOG=$(git log --no-color --pretty=format:' %an: %s' --abbrev-commit --no-merges $oldrev..$newrev)
    if [[ "$CURRENT_BRANCH" == "$BRANCH" ]]; then
        git clone -b $BRANCH "$ROOT/git" $TMP_CLONE

        cd $TMP_CLONE
        rm -f Gemfile

        echo "Building Jekyll site into $ROOT/public .."
        jekyll build -d "$ROOT/public" --config _config.yml,"$ROOT/private/_config.yml"

        echo "Cleaning up .."
        cd /tmp
        rm -Rf $TMP_CLONE

        echo "Purging CloudFlare cache .."
        curl -vs -o /dev/null -X DELETE "https://api.cloudflare.com/client/v4/zones/IDENTIFIER/purge_cache" -H "X-Auth-Email: ACCOUNT" -H "X-Auth-Key: API_KEY" -H "Content-Type: application/json" --data '{"purge_everything":true}' > /dev/null 2>&1

        echo "Posting notification to Slack .."
        TEXT="[developer.joomlatools.com] New release deployed\n"

        CHANGELOG="${CHANGELOG//$'\n'/\\n}"
        CHANGELOG="${CHANGELOG//\"/ }"

        JSON="{\"text\": \"$TEXT\", \"channel\": \"#alerts\", \"username\": \"deploy-bot\", \"icon_emoji\": \":rocket:\", \"attachments\": [{\"text\": \"$CHANGELOG\", \"color\": \"#F0E771\"}]}"

        curl -vs -o /dev/null -X POST -H "Content-Type: application/json" -d "$JSON" https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX > /dev/null 2>&1

        echo "Done"
    else
        echo "You pushed $CURRENT_BRANCH instead of $BRANCH, skipping deployment"
    fi

    exit
done